# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and release application

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  WKHTMLTOPDF_PATH: './wkhtmltox/bin/wkhtmltopdf.exe'
  NODE_VERSION: '20.x'
  INPUT_CV_PATH: './cv.html'
  OUTPUT_CV_PATH: './public/HaTienLoi-CV.pdf'

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Convert CV from html to pdf
        shell: bash
        run: |
          rm -rf ${{ env.OUTPUT_CV_PATH }}
          ${{ env.WKHTMLTOPDF_PATH }} ${{ env.INPUT_CV_PATH }} ${{ env.OUTPUT_CV_PATH }}
  
      - run: npm i

      - run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
